fix(extend-executor): english wording
jina-ai/docs pull request #249
Opened 2021-04-27 13:01 UTC by alexcg1

### All Submissions:

* [x] Have you followed the [documentation style guide](https://github.com/jina-ai/docs/tree/master/page_templates/style_guide.md)? 

### New Feature Submissions:

1. [ ] Have you added your new file to a table of content index? 
2. [ ] Did you use one of the templates in the [page_template](https://github.com/jina-ai/docs/tree/master/page_templates) folder?
3. [ ] Is your title in Title Case? 
4. [ ] Are your section headers in sentence case?

2021-04-27 15:52 UTC, theUnkownName requested changes, later dismissed

2021-04-27 15:52 UTC, theUnkownName commented on chapters/extend/executor.rst
> +Given an image ti can be instructed in natural language to predict the most relevant text snippet.
Typo in "ti"

2021-04-29 07:58 UTC, alexcg1 commented on chapters/extend/executor.rst
> +Given an image ti can be instructed in natural language to predict the most relevant text snippet.
Good catch!

2021-04-29 10:05 UTC, FionnD approved these changes

2021-05-04 13:39 UTC, nan-wang approved these changes
LGTM👍

2021-05-04 13:40 UTC, merged