docs: replicas
jina-ai/docs pull request #279
Opened 2021-05-21 08:22 UTC by cristianmtr

https://github.com/jina-ai/internal-tasks/issues/74

Also converted the md to rst

### All Submissions:

* [x] Have you followed the [documentation style guide](https://github.com/jina-ai/docs/tree/master/page_templates/style_guide.md)? 

### New Feature Submissions:

1. [x] Have you added your new file to a table of content index? 
2. [x] Did you use one of the templates in the [page_template](https://github.com/jina-ai/docs/tree/master/page_templates) folder?
3. [x] Is your title in Title Case? 
4. [x] Are your section headers in sentence case?

2021-05-21 13:54 UTC, FionnD requested changes
Great work, some minor comments. The table of contents is a requirement, the other two comments are suggestions.

2021-05-21 13:54 UTC, FionnD commented on chapters/parallel.rst
> +
I think a table of contents would help

2021-05-21 13:54 UTC, FionnD commented on chapters/parallel.rst
> +
**Suggestion**: Some form of a diagram would be good.

2021-05-21 13:54 UTC, FionnD commented on chapters/parallel.rst
> +Replicas of Pods
**Suggestion**: The advantages of using this approach over the above one would be good to know...

2021-05-21 13:56 UTC, theUnkownName commented on chapters/parallel.rst
> +to an increase in throughput, as the data is split across processes.
typo "throughput"?

2021-05-21 14:09 UTC, theUnkownName commented on chapters/parallel.rst
> +will explain these.
Try to use active voice

2021-05-21 14:09 UTC, theUnkownName commented on chapters/parallel.rst
> +to an increase in throughput, as the data is split across processes.
Maybe change "throughput" for a simpler word

2021-05-21 14:13 UTC, theUnkownName commented on chapters/parallel.rst
> +Internally, Jina switches the class from the Pod to a CompoundPod, which contains multiple Pods.
Can you also highlight `CompoundPod`please?

2021-05-21 14:13 UTC, theUnkownName commented on chapters/parallel.rst
> +This feature was introduced for the `Querying while Indexing feature </chapters/dump-reload/>`_.
Let's try to use active voice

2021-05-21 14:14 UTC, theUnkownName commented on chapters/parallel.rst
> +In order to enable this feature for a specific Pod add the following to your YAML or Python programmatic API:
Try to breakdown this sentence

2021-05-21 14:16 UTC, theUnkownName commented on chapters/parallel.rst
> +Peas are the next level at which we can configure parallelism. In this
Highlight the first occurrence of a Jina keyword (Peas)

2021-05-21 14:17 UTC, theUnkownName commented on chapters/parallel.rst
> +*parallelize*, not *shard*. This means the data is not persisted, but
Stick to one type of highligting

2021-05-21 14:19 UTC, theUnkownName commented on chapters/parallel.rst
> +1. ``round_robin`` will assign tasks in circular order, without any
Let's use active voice

2021-05-21 14:19 UTC, theUnkownName commented on chapters/parallel.rst
> +2. ``load_balance`` will assign tasks to the idle ``Peas``.
Active voice here too

2021-05-21 14:21 UTC, theUnkownName commented on chapters/parallel.rst
> +At the moment Jina does not support sharding and replication of shards
Rephrase a bit this part

2021-05-21 15:54 UTC, cristianmtr commented
@theUnkownName @FionnD I've implemented your requested changes. Please check again :)

2021-05-22 15:10 UTC, nan-wang requested changes

2021-05-22 15:10 UTC, nan-wang commented on chapters/parallel.rst
> +---------------
The section levels need to be increased by one level
```suggestion
===========
```

2021-05-22 15:10 UTC, nan-wang commented on chapters/parallel.rst
> +.. |image1| image:: ./images/simple-plot4.svg
the related images are missing in this PR.

2021-05-25 07:47 UTC, cristianmtr commented
@nan-wang Bumped the header level.

I don't get your comment about the images. They render fine for me locally.

2021-05-26 07:15 UTC, theUnkownName approved these changes
LGTM!

2021-05-26 07:29 UTC, FionnD approved these changes
Please fix the two comments before merging

2021-05-26 07:29 UTC, FionnD commented on chapters/parallel.rst
> +This means some changes and adaptations were necessary. I will explain these here.
Remove: I will explain these here.

2021-05-26 07:29 UTC, FionnD commented on chapters/parallel.rst
> +On the other hand, the Replicas operate within
Fullstop

2021-05-26 15:20 UTC, nan-wang approved these changes
LGTM👍

2021-05-26 15:20 UTC, nan-wang commented
> @nan-wang Bumped the header level.
> 
> I don't get your comment about the images. They render fine for me locally.

My bad. The images are there. All good.

2021-05-26 15:20 UTC, merged