feat: update pod usage in flow
jina-ai/docs pull request #35
Opened 2021-02-05 10:02 UTC by rutujasurve94

Documentation for updating Pod usage in Flow
[Jira-Hub-273](https://jinaai.atlassian.net/browse/JINAHUBV1-273)

2021-02-05 12:15 UTC, alexcg1 requested changes

2021-02-05 12:15 UTC, alexcg1 commented on chapters/hub/guides/docker_pod/use-your-pod.md
> +Pod image can be used in the Flow API as well. For instance:
Change to `A Pod image can also be used in the Flow API as well:`

2021-02-08 11:51 UTC, alexcg1 approved these changes
LGTM :+1:

2021-02-09 07:39 UTC, FionnD commented
Did you find why it's showing a conflict @rutujasurve94? We don't have a folder called guides in hub.

2021-02-12 12:03 UTC, FionnD commented
Hey @rutujasurve94 

Maybe just close this PR and open a new one? That might reset/fix the netlify issues?

2021-02-15 06:57 UTC, merged

2021-02-15 06:57 UTC, rutujasurve94 commented
I'm being able to merge it now