docs: add issue template
jina-ai/docs pull request #72
Opened 2021-02-09 16:28 UTC by bwanglzu

2021-02-09 16:29 UTC, cristianmtr approved these changes

2021-02-09 16:30 UTC, cristianmtr commented on .github/ISSUE_TEMPLATE/---missing---discussion-needed.md
> +name: "Create a documentation"
```suggestion
name: "Create documentation"
```

2021-02-09 16:30 UTC, cristianmtr commented on .github/ISSUE_TEMPLATE/---missing---discussion-needed.md
> +about: I’d like add/request a new documentation to Jina, before that I need some discussion.
```suggestion
about: I’d like to add/request new documentation to Jina, but that I need some discussion.
```

2021-02-09 16:30 UTC, cristianmtr commented on .github/ISSUE_TEMPLATE/---incorrect---may-be-a-typo-.md
> +name: "Fix a typo or Rephrase a piece of text"
```suggestion
name: "Fix a typo or rephrase a piece of text"
```

2021-02-09 16:31 UTC, cristianmtr requested changes
some stuff

2021-02-09 19:43 UTC, alexcg1 requested changes
Looking pretty good! Just minor tweakage

2021-02-09 19:43 UTC, alexcg1 commented on .github/ISSUE_TEMPLATE/---missing---discussion-needed.md
> +about: I’d like add/request a new documentation to Jina, before that I need some discussion.
**for** Jina

2021-02-09 19:43 UTC, alexcg1 commented on .github/ISSUE_TEMPLATE/---missing---discussion-needed.md
> +<!-- copy past your code/pull request link -->
paste

2021-02-09 19:43 UTC, alexcg1 commented on .github/ISSUE_TEMPLATE/---missing---discussion-needed.md
> +<!-- Optional, but really help us locate the problem faster -->
can remove the bit about problem

2021-02-09 19:43 UTC, alexcg1 commented on .github/ISSUE_TEMPLATE/config.yml
> +contact_links:
Add Slack link slack.jina.ai

2021-02-09 19:43 UTC, alexcg1 commented on .github/ISSUE_TEMPLATE/config.yml
> +    about: Find your solution from our documenations
documentation (no s)

2021-02-10 15:50 UTC, FionnD commented
cc @aga11313

2021-02-15 07:52 UTC, FionnD approved these changes

2021-03-06 15:24 UTC, bwanglzu commented
I'll close this one, discuss if needed later.

2021-03-06 15:24 UTC, closed without merging