Create pull request template
jina-ai/docs pull request #89
Opened 2021-02-12 12:43 UTC by FionnD

Pull request template for all future PRs. To ensure we don't forget anything.

2021-02-12 14:44 UTC, nan-wang requested changes

2021-02-12 14:44 UTC, nan-wang commented on .github/pull_request_template.md
> +* [ ] Have you followed the documentation style guide?
Do we need to add the URL link here?

2021-02-12 14:44 UTC, nan-wang commented on .github/pull_request_template.md
> +2. [ ] Did you use one of the templates in the page_template folder?
The same question goes here.

2021-02-12 15:39 UTC, FionnD commented on .github/pull_request_template.md
> +* [ ] Have you followed the documentation style guide?
Done!

2021-02-12 15:39 UTC, FionnD commented on .github/pull_request_template.md
> +2. [ ] Did you use one of the templates in the page_template folder?
Done!

2021-02-15 03:58 UTC, nan-wang approved these changes

2021-02-15 03:58 UTC, merged